# Project information
site_name: Ironstead Roleplay
site_url: 'https://ironsteadroleplay.github.io/APV/'
site_description: 'Wet en regelgeving van Ironstead Roleplay'
site_author: 'Ironstead Roleplay'

# Copyright
copyright: Copyright &copy; 2025 - 2026 Ironstead

# Congiguration
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: img/favicon.png
  logo: img/logo.png
  language: nl
plugins:
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
  - Eiland Regelgeving: eiland.md
  - Voertuigklasses: offroad.md
  - Douanegebieden: douanegebieden.md
